diff --git a/src/test/java/org/assertj/core/api/future/CompletableFutureAssert_failsWithin_Test.java b/src/test/java/org/assertj/core/api/future/CompletableFutureAssert_failsWithin_Test.java
index 1107859..87f8f4e 100644
--- a/src/test/java/org/assertj/core/api/future/CompletableFutureAssert_failsWithin_Test.java
+++ b/src/test/java/org/assertj/core/api/future/CompletableFutureAssert_failsWithin_Test.java
@@ -62,7 +62,8 @@ class CompletableFutureAssert_failsWithin_Test extends AbstractFutureTest {
     CompletableFuture<Void> future = futureCompletingAfter(ONE_SECOND, executorService);
     // WHEN/THEN
     assertThat(future).failsWithin(50, MILLISECONDS)
-                      .withThrowableOfType(TimeoutException.class)
+                      .withThrowableThat()
+                      .isInstanceOf(TimeoutException.class)
                       .withMessage(null);
   }
 
@@ -107,7 +108,8 @@ class CompletableFutureAssert_failsWithin_Test extends AbstractFutureTest {
                 .withThrowableOfType(ExecutionException.class)
                 .withMessageContaining("boom!");
     then(future).failsWithin(Duration.ofMillis(1))
-                .withThrowableOfType(ExecutionException.class)
+                .withThrowableThat()
+                .isInstanceOf(ExecutionException.class)
                 .withMessageContaining("boom!");
   }
 
diff --git a/src/test/java/org/assertj/core/api/future/FutureAssert_failsWithin_Test.java b/src/test/java/org/assertj/core/api/future/FutureAssert_failsWithin_Test.java
index b56c148..6e4bca8 100644
--- a/src/test/java/org/assertj/core/api/future/FutureAssert_failsWithin_Test.java
+++ b/src/test/java/org/assertj/core/api/future/FutureAssert_failsWithin_Test.java
@@ -63,7 +63,8 @@ class FutureAssert_failsWithin_Test extends AbstractFutureTest {
     Future<String> future = futureCompletingAfter(ONE_SECOND, executorService);
     // WHEN/THEN
     assertThat(future).failsWithin(50, MILLISECONDS)
-                      .withThrowableOfType(TimeoutException.class)
+                      .withThrowableThat()
+                      .isInstanceOf(TimeoutException.class)
                       .withMessage(null);
   }
 
@@ -108,7 +109,8 @@ class FutureAssert_failsWithin_Test extends AbstractFutureTest {
                 .withThrowableOfType(ExecutionException.class)
                 .withMessageContaining("boom!");
     then(future).failsWithin(Duration.ofMillis(1))
-                .withThrowableOfType(ExecutionException.class)
+                .withThrowableThat()
+                .isInstanceOf(ExecutionException.class)
                 .withMessageContaining("boom!");
   }
 
